---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginxorg
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-docker-desktop-nginxorg
  url: ssh://git@github.com/gogittest/nginxorg.git

